### ISSUE TITLE
In ClassTestMojo.execute: java.nio.file.NoSuchFileException: /tmp/chatunitest-info/abc-core/class-map.json

### ISSUE THREAD

**Issue by Pallav-552** [ZJU-ACES-ISE/chatunitest-maven-plugin#3]
I am getting above error while running 
**mvn chatunitest:class -DselectClass=className**

**Comment by zzzghttt** [comment]
This issue may be due to a problem during the parsing stage. Please try running the command `mvn chatunitest:clean`
and try again, or you can clone and install the `research` branch, which is our latest branch and may have fixed this issue.
