### ISSUE TITLE
java.util.zip.ZipException: zip END header not found

### ISSUE THREAD

**Issue by Wayne6Liu** [ZJU-ACES-ISE/chatunitest-maven-plugin#4]
您好,我尝试了一下,报了很多java.util.zip.ZipException: zip END header not found,使用
find . -name "*.jar" -exec sh -c 'jar tf {} >/dev/null || echo "Invalid JAR: {}"' \;
命令,查找无效的jar包,没有找到;请问还有别的排查方法吗?

[DEBUG] building maven31 dependency graph for xxx.xxxx.xxxxx:xxxxx-xxxxx-xxxxxx:jar:1.0.0-SNAPSHOT with Maven31DependencyGraphBuilder
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=789001, ConflictMarker.markTime=6568679, ConflictMarker.nodeCount=293, ConflictIdSorter.graphTime=1802341, ConflictIdSorter.topsortTime=244890, ConflictIdSorter.conflictIdCount=120, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=14165791, ConflictResolver.conflictItemCount=222, DefaultDependencyCollector.collectTime=73763556, DefaultDependencyCollector.transformTime=23739181}
[DEBUG] com.xxxx.xxxx:xxxxx-xxxx-xxxxx:jar:1.0.0-SNAPSHOT
[DEBUG]    com.xxxx.xxxx:xxxxx-xxx:jar:1.0.0-SNAPSHOT:compile
[DEBUG]       org.apache.commons:commons-lang3:jar:3.10:compile (version managed from 3.10)
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.30:compile (version managed from 1.7.30)
[DEBUG]       org.springframework:spring-beans:jar:5.2.8.RELEASE:compile (version managed from 5.2.8.RELEASE)
[DEBUG]       org.springframework:spring-context:jar:5.2.8.RELEASE:compile (version managed from 5.2.8.RELEASE)
[DEBUG]          org.springframework:spring-aop:jar:5.2.8.RELEASE:compile (version managed from 5.2.8.RELEASE)
[DEBUG]          org.springframework:spring-expression:jar:5.2.8.RELEASE:compile (version managed from 5.2.8.RELEASE)
[DEBUG]       org.springframework:spring-core:jar:5.2.8.RELEASE:compile (version managed from 5.2.8.RELEASE)
[DEBUG]          org.springframework:spring-jcl:jar:5.2.8.RELEASE:compile (version managed from 5.2.8.RELEASE)
[DEBUG]       org.apache.httpcomponents:httpclient:jar:4.5.12:compile (version managed from 4.5.12) (exclusions managed from [commons-logging:commons-logging:*:*])
[DEBUG]       org.apache.httpcomponents:httpcore-nio:jar:4.4.13:compile (version managed from 4.4.13)
[DEBUG]       org.apache.httpcomponents:httpasyncclient:jar:4.1.4:compile (version managed from 4.1.4) (exclusions managed from [commons-logging:commons-logging:*:*])
[DEBUG]       org.apache.httpcomponents:httpcore:jar:4.4.13:compile (version managed from 4.4.13)
[DEBUG]       com.fasterxml.jackson.core:jackson-core:jar:2.11.1:compile (version managed from 2.11.1)
[DEBUG]       com.fasterxml.jackson.core:jackson-databind:jar:2.11.1:compile (version managed from 2.11.1)
[DEBUG]          com.fasterxml.jackson.core:jackson-annotations:jar:2.11.1:compile (version managed from 2.11.1)
[DEBUG]       com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.11.1:compile (version managed from 2.11.1)
[DEBUG]          jakarta.activation:jakarta.activation-api:jar:1.2.2:compile (version managed from 1.2.1)
[DEBUG]       net.sf.dozer:dozer:jar:5.5.1:compile (version managed from 5.5.1)
[DEBUG]          commons-beanutils:commons-beanutils:jar:1.9.3:compile (version managed from 1.9.1)
[DEBUG]          org.slf4j:jcl-over-slf4j:jar:1.7.30:compile (version managed from 1.7.5)
[DEBUG]       com.belerweb:pinyin4j:jar:2.5.1:compile
[DEBUG]       com.google.guava:guava:jar:20.0:compile (version managed from 19.0)
[DEBUG]       org.springframework.security:spring-security-jwt:jar:1.0.9.RELEASE:compile
[DEBUG]          org.bouncycastle:bcpkix-jdk15on:jar:1.56:compile
[DEBUG]             org.bouncycastle:bcprov-jdk15on:jar:1.54:compile (version managed from 1.56)
[DEBUG]       com.aliyun.oss:aliyun-sdk-oss:jar:3.7.0:compile (version managed from 3.7.0)
[DEBUG]          org.jdom:jdom:jar:1.1:compile
[DEBUG]          org.codehaus.jettison:jettison:jar:1.1:compile
[DEBUG]             stax:stax-api:jar:1.0.1:compile
[DEBUG]          com.aliyun:aliyun-java-sdk-ram:jar:3.0.0:compile
[DEBUG]          com.aliyun:aliyun-java-sdk-ecs:jar:4.2.0:compile
[DEBUG]       com.aliyun:aliyun-java-sdk-sts:jar:3.0.0:compile
[DEBUG]       com.aliyun:aliyun-java-sdk-core:jar:4.4.6:compile
[DEBUG]          com.google.code.gson:gson:jar:2.8.5:compile (version managed from 2.8.5)
[DEBUG]          commons-logging:commons-logging:jar:1.2:compile (version managed from 1.2)
[DEBUG]          javax.xml.bind:jaxb-api:jar:2.3.1:compile (version managed from 2.3.1)
[DEBUG]             javax.activation:javax.activation-api:jar:1.2.0:compile (version managed from 1.2.0)
[DEBUG]          org.jacoco:org.jacoco.agent:jar:runtime:0.8.3:compile
[DEBUG]          org.ini4j:ini4j:jar:0.5.4:compile
[DEBUG]       org.springframework.boot:spring-boot:jar:2.3.2.RELEASE:compile (version managed from 2.3.2.RELEASE)
[DEBUG]       net.sf.json-lib:json-lib:jar:jdk15:2.4:compile (version managed from 2.4)
[DEBUG]          commons-collections:commons-collections:jar:3.2.1:compile
[DEBUG]          commons-lang:commons-lang:jar:2.5:compile
[DEBUG]          net.sf.ezmorph:ezmorph:jar:1.0.6:compile
[DEBUG]       org.springframework.boot:spring-boot-starter-undertow:jar:2.3.2.RELEASE:compile (version managed from 2.3.2.RELEASE)
[DEBUG]          io.undertow:undertow-core:jar:2.2.3.Final:compile (version managed from 2.1.3.Final)
[DEBUG]             org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile (version managed from 3.4.1.Final)
[DEBUG]             org.jboss.xnio:xnio-api:jar:3.8.0.Final:compile
[DEBUG]                org.wildfly.common:wildfly-common:jar:1.5.2.Final:compile
[DEBUG]                org.wildfly.client:wildfly-client-config:jar:1.0.1.Final:compile
[DEBUG]             org.jboss.xnio:xnio-nio:jar:3.8.0.Final:runtime
[DEBUG]             org.jboss.threads:jboss-threads:jar:3.1.0.Final:compile
[DEBUG]          io.undertow:undertow-servlet:jar:2.2.3.Final:compile (version managed from 2.1.3.Final)
[DEBUG]             org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:jar:2.0.1.Final:compile
[DEBUG]          io.undertow:undertow-websockets-jsr:jar:2.2.3.Final:compile (version managed from 2.1.3.Final)
[DEBUG]             org.jboss.spec.javax.websocket:jboss-websocket-api_1.1_spec:jar:2.0.0.Final:compile
[DEBUG]          jakarta.servlet:jakarta.servlet-api:jar:4.0.4:compile (version managed from 4.0.4)
[DEBUG]          org.glassfish:jakarta.el:jar:3.0.3:compile (version managed from 3.0.3)
[DEBUG]       com.amazonaws:aws-java-sdk-s3:jar:1.11.792:compile (version managed from 1.11.792) (optionality managed from false)
[DEBUG]          com.amazonaws:aws-java-sdk-kms:jar:1.11.792:compile (version managed from 1.11.792) (optionality managed from false)
[DEBUG]          com.amazonaws:aws-java-sdk-core:jar:1.11.792:compile (version managed from 1.11.792) (exclusions managed from [])
[DEBUG]             software.amazon.ion:ion-java:jar:1.0.2:compile
[DEBUG]             com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.11.1:compile (version managed from 2.6.7)
[DEBUG]             joda-time:joda-time:jar:2.8:compile (version managed from 2.8.1)
[DEBUG]          com.amazonaws:jmespath-java:jar:1.11.792:compile (version managed from 1.11.792)
[DEBUG]    org.springframework.boot:spring-boot-starter-test:jar:2.3.2.RELEASE:test
[DEBUG]       org.springframework.boot:spring-boot-starter:jar:2.3.2.RELEASE:test (version managed from 2.3.2.RELEASE)
[DEBUG]          org.springframework.boot:spring-boot-autoconfigure:jar:2.3.2.RELEASE:test (version managed from 2.3.2.RELEASE)
[DEBUG]          jakarta.annotation:jakarta.annotation-api:jar:1.3.5:test (version managed from 1.3.5)
[DEBUG]          org.yaml:snakeyaml:jar:1.26:test (version managed from 1.26)
[DEBUG]       org.springframework.boot:spring-boot-test:jar:2.3.2.RELEASE:test (version managed from 2.3.2.RELEASE)
[DEBUG]       org.springframework.boot:spring-boot-test-autoconfigure:jar:2.3.2.RELEASE:test (version managed from 2.3.2.RELEASE)
[DEBUG]       com.jayway.jsonpath:json-path:jar:2.4.0:test (version managed from 2.4.0)
[DEBUG]          net.minidev:json-smart:jar:2.3:test (version managed from 2.3)
[DEBUG]             net.minidev:accessors-smart:jar:1.2:test
[DEBUG]                org.ow2.asm:asm:jar:5.0.4:test
[DEBUG]       jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile (version managed from 2.3.3)
[DEBUG]       org.assertj:assertj-core:jar:3.16.1:test (version managed from 3.16.1)
[DEBUG]       org.hamcrest:hamcrest:jar:2.2:test (version managed from 2.2)
[DEBUG]       org.skyscreamer:jsonassert:jar:1.5.0:test (version managed from 1.5.0)
[DEBUG]          com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[DEBUG]       org.springframework:spring-test:jar:5.2.8.RELEASE:test (version managed from 5.2.8.RELEASE)
[DEBUG]       org.xmlunit:xmlunit-core:jar:2.7.0:test (version managed from 2.7.0)
[DEBUG]    xxx.xxxx.xxxxx:xxxxx-config:jar:1.0.0-SNAPSHOT:compile
[DEBUG]    org.springframework.boot:spring-boot-starter-log4j2:jar:2.3.2.RELEASE:compile
[DEBUG]       org.apache.logging.log4j:log4j-slf4j-impl:jar:2.17.0:compile (version managed from 2.13.3)
[DEBUG]          org.apache.logging.log4j:log4j-api:jar:2.17.0:compile (version managed from 2.17.0)
[DEBUG]       org.apache.logging.log4j:log4j-core:jar:2.17.0:compile (version managed from 2.13.3)
[DEBUG]       org.apache.logging.log4j:log4j-jul:jar:2.17.0:compile (version managed from 2.13.3)
[DEBUG]       org.slf4j:jul-to-slf4j:jar:1.7.30:compile (version managed from 1.7.30)
[DEBUG]    com.nuonuo:open-sdk:jar:1.0.5.2:compile
[DEBUG]       commons-codec:commons-codec:jar:1.14:compile (version managed from 1.12)
[DEBUG]    xxx.xxxx.xxxxx:xxxxx-constants:jar:1.0.0-SNAPSHOT:compile
[DEBUG]    io.github.ZJU-ACES-ISE:chatunitest-starter:pom:1.0.0:compile
[DEBUG]       org.junit.jupiter:junit-jupiter-api:jar:5.6.2:compile (version managed from 5.7.0)
[DEBUG]          org.opentest4j:opentest4j:jar:1.2.0:compile
[DEBUG]          org.junit.platform:junit-platform-commons:jar:1.6.2:compile (version managed from 1.6.2)
[DEBUG]       org.junit.platform:junit-platform-launcher:jar:1.6.2:compile (version managed from 1.9.2)
[DEBUG]       org.junit.jupiter:junit-jupiter-engine:jar:5.6.2:runtime (version managed from 5.7.0)
[DEBUG]    org.mockito:mockito-core:jar:3.4.4:test
[DEBUG]       net.bytebuddy:byte-buddy:jar:1.10.13:test (version managed from 1.10.13)
[DEBUG]       net.bytebuddy:byte-buddy-agent:jar:1.10.13:test (version managed from 1.10.13)
[DEBUG]       org.objenesis:objenesis:jar:2.6:test
[DEBUG]    org.mockito:mockito-junit-jupiter:jar:4.4.0:test
[DEBUG]    org.mockito:mockito-inline:jar:3.3.3:test
[DEBUG]    org.powermock:powermock-api-mockito2:jar:2.0.9:test
[DEBUG]       org.powermock:powermock-api-support:jar:2.0.9:test
[DEBUG]          org.powermock:powermock-reflect:jar:2.0.9:test
[DEBUG]          org.powermock:powermock-core:jar:2.0.9:test
[DEBUG]             org.javassist:javassist:jar:3.27.0-GA:test
[DEBUG]    org.powermock:powermock-module-junit4:jar:2.0.9:test
[DEBUG]       org.powermock:powermock-module-junit4-common:jar:2.0.9:test
[DEBUG]       junit:junit:jar:4.12:test (version managed from 4.12)
[DEBUG]       org.hamcrest:hamcrest-core:jar:2.2:test (version managed from 1.3)
[DEBUG]    org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[DEBUG]       org.junit.jupiter:junit-jupiter-params:jar:5.6.2:test (version managed from 5.8.2)
[DEBUG]    org.junit.vintage:junit-vintage-engine:jar:5.6.2:test
[DEBUG]       org.apiguardian:apiguardian-api:jar:1.1.0:compile
[DEBUG]       org.junit.platform:junit-platform-engine:jar:1.6.2:compile (version managed from 1.6.2)
java.util.zip.ZipException: zip END header not found
In ClassParser.extractClass Exception: java.lang.RuntimeException: In ClassParser getMethodSignature: fromJson

**Comment by coder-chenzhi** [comment]
@zzzghttt @NCCurry30

**Comment by zzzghttt** [comment]
您好，这是由于解析阶段读取依赖jar包时出现问题。我注意到你使用的是较旧的版本，请使用最新的1.4.0版本，我们优化了解析的算法，这个错误应该不会出现了。

**Comment by Wayne6Liu** [comment]
[ERROR] Failed to execute goal io.github.ZJU-ACES-ISE:chatunitest-maven-plugin:1.4.0:class (default-cli) on project xxxx-xxxxxx-xxxxxx: Execution default-cli of goal io.github.ZJU-ACES-ISE:chatunitest-maven-plugin:1.4.0:class failed: An API incompatibility was encountered while executing io.github.ZJU-ACES-ISE:chatunitest-maven-plugin:1.4.0:class: java.lang.IllegalAccessError: class org.eclipse.aether.connector.basic.ChecksumCalculator$Checksum tried to access private method org.eclipse.aether.util.ChecksumUtils.toHexString([B)Ljava/lang/String; (org.eclipse.aether.connector.basic.ChecksumCalculator$Checksum and org.eclipse.aether.util.ChecksumUtils are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @b174a73)
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.github.ZJU-ACES-ISE:chatunitest-maven-plugin:1.4.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
感谢回复,更换了新版本之后 出现了这个报错 有没有什么排查思路?

**Comment by Wayne6Liu** [comment]
> 您好，这是由于解析阶段读取依赖jar包时出现问题。我注意到你使用的是较旧的版本，请使用最新的1.4.0版本，我们优化了解析的算法，这个错误应该不会出现了。

[ERROR] Failed to execute goal io.github.ZJU-ACES-ISE:chatunitest-maven-plugin:1.4.0:class (default-cli) on project xxxx-xxxxxx-xxxxxx: Execution default-cli of goal io.github.ZJU-ACES-ISE:chatunitest-maven-plugin:1.4.0:class failed: An API incompatibility was encountered while executing io.github.ZJU-ACES-ISE:chatunitest-maven-plugin:1.4.0:class: java.lang.IllegalAccessError: class org.eclipse.aether.connector.basic.ChecksumCalculator$Checksum tried to access private method org.eclipse.aether.util.ChecksumUtils.toHexString([B)Ljava/lang/String; (org.eclipse.aether.connector.basic.ChecksumCalculator$Checksum and org.eclipse.aether.util.ChecksumUtils are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @b174a73)
[ERROR] -----------------------------------------------------
[ERROR] realm = plugin>io.github.ZJU-ACES-ISE:chatunitest-maven-plugin:1.4.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
感谢回复,更换了新版本之后 出现了这个报错 有没有什么排查思路?

**Comment by zzzghttt** [comment]
这个问题我们暂时还没有遇到过。根据您提供的信息，可能是由于 Maven 插件与项目的依赖或 Maven 本身的版本不兼容，可以尝试升级您的Maven版本。
