### ISSUE TITLE
No test cases are generated on a simple Maven project

### ISSUE THREAD

**Issue by dfucci** [ZJU-ACES-ISE/chatunitest-maven-plugin#5]
Steps to reproduce 
1. Create a simple project
`mvn archetype:generate -DgroupId=net.testing.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.5 -DinteractiveMode=false`

2. Add dependencies as per README
3. Run for the entire project (using gpt-3.5-turbo) 
`mvn chatunittest:project`

4. Failing to generate test cases with the following 
```
[INFO] Generating test for method < main > round 0 ...
[INFO] Test for method < main > compilation failed round 0
[INFO] Fixing test for method < main > round 1 ...
[INFO] Test for method < main > compilation failed round 1
...
Processed main(String[])
Processed /my-app/src/main/java/net/testing/app/App.java
[INFO]
==========================
[ChatUniTest] Generation finished
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:50 min
[INFO] Finished at: 2024-09-17T11:32:30+02:00
[INFO] ------------------------------------------------------------------------

```

5. No folder with test cases is created.

The content of the only class App.java
```
package net.testing.app;

/**
 * Hello world!
 */
public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
```

**Comment by Mikekkkkk** [comment]
@dfucci  Check the folder "chatunitest-tests"  under your project folder.In default,we will create the folder in your project folder
